updated yml file

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -36,7 +36,7 @@ jobs:
         run: sleep 30
 
       - name: Run Tests
-        run: | docker exec $(docker ps -qf "name=web") pytest || ( echo "Tests failed" 
+        run: docker exec $(docker ps -qf "name=web") pytest || ( echo "Tests failed" 
         docker-compsoe logs
         docker-compose down
         exit 1
